### ISSUE TITLE
Weights matrix for focal2r()

### ISSUE THREAD

**Issue by fdetsch** [michaeldorman/starsExtra#2]
Would it be possible to equip `focal2r()` with a weights matrix argument similar to `focal2()`? I need to run weighted focal functions (eg. `var()`) that are not part of the C implementation on my **stars** objects .

**Comment by michaeldorman** [comment]
Sure, I'll add this and post here when ready.

**Comment by michaeldorman** [comment]
I added the `w` (weights) argument in `focal2r`. 

https://github.com/michaeldorman/starsExtra/blob/master/R/focal2r.R

Will be happy to hear if you encounter any issues or other ideas, thanks!

**Comment by fdetsch** [comment]
Tested it against `raster::focal()` w/weights, seems to give identical results. Thanks 🥳

**Comment by michaeldorman** [comment]
Great, thank you for checking!
